version: '3.1'

services:
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_DATABASE=test
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
